// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2c6SX7BJZjYBijz2RZSSwgFZ6UPkTmvw',
    appId: '1:469200361363:web:4f6ab21d620177c3287a66',
    messagingSenderId: '469200361363',
    projectId: 'weather-app-a863c',
    authDomain: 'weather-app-a863c.firebaseapp.com',
    storageBucket: 'weather-app-a863c.firebasestorage.app',
    measurementId: 'G-KJW6D6BXPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5svVPW0ugizzDVF5Im1dFsPuIagfUXU',
    appId: '1:469200361363:android:e74be208795e57bd287a66',
    messagingSenderId: '469200361363',
    projectId: 'weather-app-a863c',
    storageBucket: 'weather-app-a863c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5bq_jibRK21W16oZ4J5ro7BsGhoXdx0E',
    appId: '1:469200361363:ios:191e107a6299d32f287a66',
    messagingSenderId: '469200361363',
    projectId: 'weather-app-a863c',
    storageBucket: 'weather-app-a863c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5bq_jibRK21W16oZ4J5ro7BsGhoXdx0E',
    appId: '1:469200361363:ios:191e107a6299d32f287a66',
    messagingSenderId: '469200361363',
    projectId: 'weather-app-a863c',
    storageBucket: 'weather-app-a863c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2c6SX7BJZjYBijz2RZSSwgFZ6UPkTmvw',
    appId: '1:469200361363:web:594569c29db3f21f287a66',
    messagingSenderId: '469200361363',
    projectId: 'weather-app-a863c',
    authDomain: 'weather-app-a863c.firebaseapp.com',
    storageBucket: 'weather-app-a863c.firebasestorage.app',
    measurementId: 'G-NP9YZKJX1F',
  );
}
